---
title: "visualization"
author: "Shiyu Yang"
date: "2024-11-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(ggsignif)
library(viridis)
```

# Read data
# Read data and clean
```{r}
raw_data<- read.csv("updating_full_data.csv")

# Removed NA in authors, corrected the format of gender_bipoc, correct factor categorization
data<- raw_data %>% 
  dplyr::filter(!is.na(first_author_gender)) %>% 
  dplyr::filter(!is.na(first_author_bipoc)) %>% 
  dplyr::filter(!is.na(last_author_gender)) %>% 
  dplyr::filter(!is.na(last_author_bipoc)) %>% 
  dplyr::filter(!is.na(corresponding_author_bipoc)) %>%   
  dplyr::filter(!is.na(corresponding_author_gender)) %>% 
  dplyr::filter(!is.na(all_bipoc)) %>%   
  dplyr::filter(!is.na(all_white)) %>%  
  dplyr::filter(!is.na(all_men)) %>%   
  dplyr::filter(!is.na(all_women)) %>%  
  mutate(first_author_gender_bipoc = 
           ifelse(first_author_gender_bipoc == 0, "00", 
           ifelse(first_author_gender_bipoc == 1, "01",  
                  as.character(first_author_gender_bipoc))),
         last_author_gender_bipoc = 
           ifelse(last_author_gender_bipoc == 0, "00", 
           ifelse(last_author_gender_bipoc == 1, "01", 
                  as.character(last_author_gender_bipoc))),
         corresponding_author_gender_bipoc = 
           ifelse(corresponding_author_gender_bipoc == 0, "00", 
           ifelse(corresponding_author_gender_bipoc == 1, "01", 
                  as.character(corresponding_author_gender_bipoc)))) %>% 
  mutate(across(where(is.character), factor)) %>% 
  mutate(across(c(single_author, fund, affiliation_dev, affiliation_us,
                  first_author_bipoc, first_author_gender, first_author_gender_bipoc,
                  last_author_gender,last_author_bipoc, last_author_gender_bipoc,
                  corresponding_author_gender, corresponding_author_bipoc, 
                  corresponding_author_gender_bipoc, 
                  all_men,all_women,all_white,all_bipoc, overlap_corr_author), 
                as.factor))  %>% 
  glimpse()

# Centered continues factors
data$publication_year_c <- data$publication_year - mean(data$publication_year, na.rm = T)
data$author_count_c <- data$author_count - mean(data$author_count, na.rm = T)

# Filtered out no overlap in corresponding author and first/last author (3% in this dataset)
overlap_data<- data %>% dplyr::filter (overlap_corr_author == "1"|overlap_corr_author == "2")
```

# Visualization

```{r}
m4_graph <- glm.nb(cited_count ~ first_author_gender * first_author_bipoc + last_author_gender * last_author_bipoc + publication_year + affiliation_us + fund + author_count + journal + document_type, data = overlap_data)

new_data <- expand.grid(
  first_author_gender = unique(no_out_overlap_data$first_author_gender),
  last_author_gender = unique(no_out_overlap_data$last_author_gender),
  first_author_bipoc = unique(no_out_overlap_data$first_author_bipoc),
  last_author_bipoc = unique(no_out_overlap_data$last_author_bipoc),
  affiliation_us = unique(no_out_overlap_data$affiliation_us),
  publication_year = mean(no_out_overlap_data$publication_year, na.rm = T),
  fund = unique(no_out_overlap_data$fund),
  document_type = unique(data$document_type),
  author_count =mean(no_out_overlap_data$author_count, na.rm = T),
  journal = unique(no_out_overlap_data$journal)
)

predictions <- predict(m4_graph, newdata = new_data, type = "response", se.fit = TRUE)
new_data$cited_count_pred <- predictions$fit
new_data$se <- predictions$se.fit


data_grouped <- new_data %>%
  group_by(first_author_gender, first_author_bipoc) %>%
  summarise(
    cited_count_pred = mean(cited_count_pred),
    se = mean(se),
    .groups = 'drop'
  )

ggplot(data_grouped, aes(x = factor(first_author_bipoc, levels = c(0, 1), labels = c("White", "BIPOC")), 
                     y = cited_count_pred, 
                     fill = factor(first_author_gender, levels = c(0, 1), labels = c("Men", "Women"))))+
  geom_bar(stat = "identity", position = position_dodge(width = 0.9)) +
  geom_errorbar(aes(ymin = cited_count_pred - se, ymax = cited_count_pred + se), 
                position = position_dodge(width = 0.9), width = 0.25) +
  labs(
    x = "Race",
    y = "Predicted Cited Count",
    fill = "Gender",
    title = "Predicted Cited Count Based on First Author Gender and Race"
  ) +
  scale_fill_manual(values = c("Men" = "#999999", "Women" = "#D55E50")) +  
  theme_bw() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 14, face = "bold"),
    axis.text.x = element_text(hjust = 0.5),
    legend.title = element_text(size = 12),
    legend.text = element_text(size = 10),
        legend.position = "top"
  )
```


```{r}
m5_graph <- glm.nb(cited_count ~ all_men * all_white + publication_year + affiliation_us + fund+ author_count + journal + document_type, data = overlap_data)

new_data <- expand.grid(
  all_men = unique(overlap_data$all_men),
  all_white = unique(overlap_data$all_white),
  affiliation_us = unique(overlap_data$affiliation_us),
  publication_year = mean(overlap_data$publication_year, na.rm = T),
  fund = unique(overlap_data$fund),
  author_count =mean(overlap_data$author_count, na.rm = T),
  document_type = unique(data$document_type),
  journal = unique(overlap_data$journal)
)

predictions <- predict(m5_graph, newdata = new_data, type = "response", se.fit = TRUE)
new_data$cited_count_pred <- predictions$fit
new_data$se <- predictions$se.fit

data_grouped <- new_data %>%
  group_by(all_men, all_white) %>%
  summarise(
    cited_count_pred = mean(cited_count_pred),
    se = mean(se)
  )

plot <- ggplot(data_grouped, aes(x = factor(all_white, levels = c(0, 1), labels = c("Not All White", "All White")), 
                                 y = cited_count_pred, 
                                 fill = factor(all_men, levels = c(0, 1), labels = c("Not All Men", "All Men")))) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.9)) +
  geom_errorbar(aes(ymin = cited_count_pred - se, ymax = cited_count_pred + se), 
                position = position_dodge(width = 0.9), width = 0.25) +
  labs(
    x = "Men Representation",
    y = "Predicted Cited Count",
    fill = "White Representation",
    title = "Author Gender and Race vs. Citation Count"
  ) +
  scale_fill_manual(values = c("Not All Men" = "#E69F00", "All Men" = "#0072B2")) +  
  theme_bw() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 14, face = "bold"),
    axis.text.x = element_text(hjust = 0.5),
    legend.title = element_text(size = 12),
    legend.text = element_text(size = 10),
    legend.position = "top"
  )

plot
```

```{r}
m6_graph <- glm.nb(cited_count ~ all_women * all_bipoc + publication_year + affiliation_us + fund+ author_count + journal + document_type, data = overlap_data)

new_data <- expand.grid(
  all_women = unique(no_out_overlap_data$all_women),
  all_bipoc = unique(no_out_overlap_data$all_bipoc),
  affiliation_us = unique(no_out_overlap_data$affiliation_us),
  publication_year = mean(no_out_overlap_data$publication_year, na.rm = T),
  fund = unique(no_out_overlap_data$fund),
  author_count =mean(no_out_overlap_data$author_count, na.rm = T),
  document_type = unique(data$document_type),
  journal = unique(no_out_overlap_data$journal)
)

predictions <- predict(m6_graph, newdata = new_data, type = "response", se.fit = TRUE)
new_data$cited_count_pred <- predictions$fit
new_data$se <- predictions$se.fit

data_grouped <- new_data %>%
  group_by(all_women, all_bipoc) %>%
  summarise(
    cited_count_pred = mean(cited_count_pred),
    se = mean(se)
  )

plot<- ggplot(data_grouped, aes(x = factor(all_bipoc, levels = c(0, 1), labels = c("Not All BIPOC", "All BIPOC")), 
                          y = cited_count_pred, 
                          fill = factor(all_women, levels = c(0, 1), labels = c("Not All Women", "All Women")))) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.9)) +
  geom_errorbar(aes(ymin = cited_count_pred - se, ymax = cited_count_pred + se), 
                position = position_dodge(width = 0.9), width = 0.25) +

  labs(
    x = "BIPOC Representation",
    y = "Predicted Cited Count",
    fill = "Women Representation",
    title = "Predicted Cited Count Based on Women and BIPOC authors"
  ) +
  scale_fill_manual(values = c("Not All Women" = "#0072B2", "All Women" = "#E69F00")) +  
  theme_bw() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 14, face = "bold"),
    axis.text.x = element_text(hjust = 0.5),
    legend.title = element_text(size = 12),
    legend.text = element_text(size = 10),
        legend.position = "top"
  )

plot
```

```{r}
m1_graph <- glm.nb(cited_count ~ first_author_bipoc * first_author_gender + affiliation_us + publication_year + fund + author_count + journal + document_type, data = overlap_data)
new_data <- expand.grid(
  first_author_bipoc = unique(data$first_author_bipoc),
  first_author_gender = unique(data$first_author_gender),
  affiliation_us = unique(data$affiliation_us),
  publication_year = mean(data$publication_year, na.rm = T),
  fund = unique(data$fund),
  author_count =mean(data$author_count, na.rm = T),
  document_type = unique(data$document_type),
  journal = unique(data$journal)
)

predictions <- predict(m1_graph, newdata = new_data, type = "response", se.fit = TRUE)
new_data$cited_count_pred <- predictions$fit
new_data$se <- predictions$se.fit

data_grouped <- new_data %>%
  group_by(first_author_bipoc, first_author_gender) %>%
  summarise(
    cited_count_pred = mean(cited_count_pred),
    se = mean(se)
  )

ggplot(data_grouped, aes(x = factor(first_author_bipoc, levels = c(0, 1), labels = c("White", "BIPOC")), 
                     y = cited_count_pred, 
                     fill = factor(first_author_gender, levels = c(0, 1), labels = c("Men", "Women"))))+
  geom_bar(stat = "identity", position = position_dodge(width = 0.9)) +
  geom_errorbar(aes(ymin = cited_count_pred - se, ymax = cited_count_pred + se), 
                position = position_dodge(width = 0.9), width = 0.25) +
  labs(
    x = "Race",
    y = "Predicted Cited Count",
    fill = "Gender",
    title = "First Author Gender and Race vs. Citation Count"
  ) +
  scale_fill_manual(values = c("Men" = "#999999", "Women" = "#D55E50")) +  
  theme_bw() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 14, face = "bold"),
    axis.text.x = element_text(hjust = 0.5),
    legend.title = element_text(size = 12),
    legend.text = element_text(size = 10),
        legend.position = "top"
  )
```


```{r}
m2_graph <-  glm.nb(cited_count ~ last_author_bipoc * last_author_gender+ publication_year + affiliation_us + fund + document_type + author_count + journal, data = overlap_data)

new_data <- expand.grid(
  last_author_bipoc = unique(data$last_author_bipoc),
  last_author_gender = unique(data$last_author_gender),
  affiliation_us = unique(data$affiliation_us),
  publication_year = mean(data$publication_year, na.rm = T),
  fund = unique(data$fund),
  author_count =mean(data$author_count, na.rm = T),
  document_type = unique(data$document_type),
  journal = unique(data$journal)
)

predictions <- predict(m2_graph, newdata = new_data, type = "response", se.fit = TRUE)
new_data$cited_count_pred <- predictions$fit
new_data$se <- predictions$se.fit

data_grouped <- new_data %>%
  group_by(last_author_bipoc, last_author_gender) %>%
  summarise(
    cited_count_pred = mean(cited_count_pred),
    se = mean(se)
  )

ggplot(data_grouped, aes(x = factor(last_author_bipoc, levels = c(0, 1), labels = c("White", "BIPOC")), 
                     y = cited_count_pred, 
                     fill = factor(last_author_gender, levels = c(0, 1), labels = c("Men", "Women"))))+
  geom_bar(stat = "identity", position = position_dodge(width = 0.9)) +
  geom_errorbar(aes(ymin = cited_count_pred - se, ymax = cited_count_pred + se), 
                position = position_dodge(width = 0.9), width = 0.25) +
  labs(
    x = "Race",
    y = "Predicted Cited Count",
    fill = "Gender",
    title = "Last Author Gender and Race vs. Citation Count"
  ) +
  scale_fill_manual(values = c("Men" = "#999999", "Women" = "#D55E50")) +  
  theme_bw() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 14, face = "bold"),
    axis.text.x = element_text(hjust = 0.5),
    legend.title = element_text(size = 12),
    legend.text = element_text(size = 10)
  )
```


```{r}
m3_graph <-  glm.nb(cited_count ~ corresponding_author_bipoc * corresponding_author_gender + publication_year + affiliation_us + fund + author_count + journal + document_type, data = overlap_data)
new_data <- expand.grid(
  corresponding_author_bipoc = unique(overlap_data$corresponding_author_bipoc),
  corresponding_author_gender = unique(overlap_data$corresponding_author_gender),
  affiliation_us = unique(overlap_data$affiliation_us),
  publication_year = mean(overlap_data$publication_year, na.rm = T),
  fund = unique(overlap_data$fund),
  author_count =mean(overlap_data$author_count, na.rm = T),
  document_type = unique(data$document_type),
  journal = unique(overlap_data$journal)
)

predictions <- predict(m3_graph, newdata = new_data, type = "response", se.fit = TRUE)
new_data$cited_count_pred <- predictions$fit
new_data$se <- predictions$se.fit

data_grouped <- new_data %>%
  group_by(corresponding_author_bipoc, corresponding_author_gender) %>%
  summarise(
    cited_count_pred = mean(cited_count_pred),
    se = mean(se)
  )

ggplot(data_grouped, aes(x = factor(corresponding_author_bipoc, levels = c(0, 1), labels = c("White", "BIPOC")), 
                     y = cited_count_pred, 
                     fill = factor(corresponding_author_gender, levels = c(0, 1), labels = c("Men", "Women"))))+
  geom_bar(stat = "identity", position = position_dodge(width = 0.9)) +
  geom_errorbar(aes(ymin = cited_count_pred - se, ymax = cited_count_pred + se), 
                position = position_dodge(width = 0.9), width = 0.25) +
  labs(
    x = "Race",
    y = "Predicted Cited Count",
    fill = "Gender",
    title = "Corresponding Author Gender and Race vs. Citation Count"
  ) +
  scale_fill_manual(values = c("Men" = "#999999", "Women" = "#D55E50")) +  
  theme_bw() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 14, face = "bold"),
    axis.text.x = element_text(hjust = 0.5),
    legend.title = element_text(size = 12),
    legend.text = element_text(size = 10)
  )
```