---
title: "author_clean"
author: "Shiyu Yang"
date: "2024-11-05"
output: html_document
---

# This is the step 2 in Data Clean
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# Read data
```{r}
brain<- read.csv("raw_author_brain.csv")
nature_neuro<- read.csv("raw_author_nature_neuro.csv")
jocn<- read.csv("raw_author_jocn.csv")
```

# Data clean
```{r}
# Brain clean
cleaned_brain <- brain %>%
  mutate(full_name = author_full_names) %>% 
  separate(author_full_names, into = c("part1", "part2", "part3"), sep = ",", fill = "right") %>%
  mutate(part2 = str_replace(part2, "\\s+[A-Z]\\.\\s*", " ")) %>% 
  mutate(part2 = str_replace(part2, "\\s+[A-Z]\\.\\s*", " ")) %>% 
  mutate(part2 = str_replace(part2, "\\s+[A-Z]\\.\\s*", " ")) %>% 
  mutate(part2 = str_replace(part2, "(?<!-)\\s+-\\s+(?![A-Z])", " ")) %>%
  mutate(part2 = str_trim(part2)) %>%
  mutate(last_name = str_trim(part1),
         first_name = str_trim(part2))

# Due to abbreviation in some author name, 735 names with duplication will be removed in the dataset
sum(is.na(cleaned_brain$first_name) | cleaned_brain$first_name == "")
cleaned_brain <- cleaned_brain[!(is.na(cleaned_brain$first_name) | cleaned_brain$first_name == ""), ]

# Create name list from Brain
cleaned_brain <- cleaned_brain%>% 
  distinct(full_name, first_name, last_name) %>% 
  write.csv("brain_name_list.csv")
```

```{r}
# Nature Neuroscience clean
cleaned_nature_neuro<- nature_neuro %>%
  mutate(full_name = author_full_names) %>% 
  separate(author_full_names, into = c("part1", "part2", "part3"), sep = ",", fill = "right") %>%
  mutate(part2 = str_replace(part2, "\\s+[A-Z]\\.\\s*", " ")) %>% 
  mutate(part2 = str_replace(part2, "\\s+[A-Z]\\.\\s*", " ")) %>% 
  mutate(part2 = str_replace(part2, "\\s+[A-Z]\\.\\s*", " ")) %>% 
  mutate(part2 = str_replace(part2, "(?<!-)\\s+-\\s+(?![A-Z])", " ")) %>%
  mutate(part2 = str_trim(part2)) %>%
  mutate(last_name = str_trim(part1),
         first_name = str_trim(part2))

# Due to abbreviation in some author name, 99 names with duplication will be removed in the dataset
sum(is.na(cleaned_nature_neuro$first_name) | cleaned_nature_neuro$first_name == "")
cleaned_nature_neuro <- cleaned_nature_neuro[!(is.na(cleaned_nature_neuro$first_name) | cleaned_nature_neuro$first_name == ""), ]

# Create name list from Brain
cleaned_nature_neuro <- cleaned_nature_neuro %>% 
  distinct(full_name, first_name, last_name) %>% 
  write.csv("nature_neuro_name_list.csv")
```

```{r}
# JoCN clean
cleaned_jocn<- jocn %>%
  mutate(full_name = author_full_names) %>% 
  separate(author_full_names, into = c("part1", "part2", "part3"), sep = ",", fill = "right") %>%
  mutate(part2 = str_replace(part2, "\\s+[A-Z]\\.\\s*", " ")) %>% 
  mutate(part2 = str_replace(part2, "\\s+[A-Z]\\.\\s*", " ")) %>% 
  mutate(part2 = str_replace(part2, "\\s+[A-Z]\\.\\s*", " ")) %>% 
  mutate(part2 = str_replace(part2, "(?<!-)\\s+-\\s+(?![A-Z])", " ")) %>%
  mutate(part2 = str_trim(part2)) %>%
  mutate(last_name = str_trim(part1),
         first_name = str_trim(part2))

# Due to abbreviation in some author name, 15 names with duplication will be removed in the dataset
sum(is.na(cleaned_jocn$first_name) | cleaned_jocn$first_name == "")
cleaned_jocn <- cleaned_jocn[!(is.na(cleaned_jocn$first_name) | cleaned_jocn$first_name == ""), ]

# Manually clean
cleaned_jocn <- cleaned_jocn %>%
  mutate(first_name = case_when(
    first_name  == "Dominique J-F" ~ "Dominique",
    first_name  == "-Marsel" ~ "Marsel",
    first_name  == "-Xavier" ~ "Xavier",
    first_name  == "-L. Sharon" ~ "Sharon",
    TRUE ~ first_name  
  )) 

# Create name list from JoCN
cleaned_jocn <- cleaned_jocn %>% 
  distinct(full_name, first_name, last_name) %>% 
  write.csv("jocn_name_list.csv")
```
# Merge datasets
```{r}
data<- jocn %>% 
  bind_rows(nature_neuro)%>% 
  bind_rows(brain)%>%
  filter(!is.na(reprint_addresses)) %>%   
  filter(reprint_addresses!="") %>% 
  glimpse()
write.csv(data, file = "raw_author_data.csv")

author_distinct<- data %>% 
  filter(!is.na(reprint_addresses)) %>%   
  filter(reprint_addresses!="") %>% 
  filter(publication_year > 2009) %>% 
  filter(document_type == "Review" | document_type == "Article") %>% 
  distinct(author_full_names) 
```
# Merge race and gender
```{r}
name_data<- read.csv("updating_name_value.csv") %>% 
  rename(author_full_names = full_name) %>% 
    mutate(gender = as.factor(gender),
           bipoc  = as.factor(bipoc))  %>% 
  mutate(gender = recode(gender, "m" = "0", "f" = "1"))

merged_data <- data %>%
  left_join(name_data, by = "author_full_names") %>% 
  distinct()
```
# Mixed gender and race
```{r}
summary_data <- merged_data %>%
  group_by(doi) %>%
  mutate(all_men = ifelse(all(gender == "0"), 1, 0),
         all_women = ifelse(all(gender == "1"), 1, 0),
         all_white = ifelse(all(bipoc == "0"), 1, 0),
         all_bipoc = ifelse(all(bipoc == "1"), 1, 0))
```

```{r}
write.csv(summary_data, file = "updating_gender_bipoc_data.csv", row.names = FALSE)
```
