---
title: "reference"
author: "Shiyu Yang"
date: "2024/8/27"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)
library(stringr)
```
# Cited reference
```{r}
# 9,323 publications in updating_cr_data
updating_cr_data <- read.csv("updating_cr_data.csv")

# Perform a series of operations on the read citation data
reference<- updating_cr_data %>%
  separate_rows(cited_references, sep = "; ") %>% 
  mutate(reference = str_extract(cited_references, "(?<=DOI ).*"),
         reference = str_replace_all(reference, "\\[|\\]", " "),
         reference = str_replace(reference, ".*DOI\\s+", "DOI "),
         reference = str_replace(reference, ".*,\\s+", ", "),
         reference = str_replace(reference, "^DOI ", ""), 
         reference = str_replace_all(reference, " ", ""),
         reference = str_replace_all(reference, ",", ""),
         reference = str_replace(reference, "https://doi.org/", ""),     
         reference = str_replace(reference, "dx.doi.org/", "")

)
reference$reference <- gsub("^/", "", reference$reference)

reference<- reference %>%
  mutate(reference = ifelse(reference == "PatentNo.453376", "10.1101/2021.07.22.453376", reference))
write.csv(reference, file = "updating_reference_data.csv", row.names = FALSE)
```

# Read data
```{r}
# Read author - related data from the raw_author_data.csv file, there are 92,325 authors
author<- read.csv("raw_author_data.csv") %>% 
  select(author_full_names,doi,cited_references)

# Read author - related data from the updating_gender_bipoc_data.csv file, there are 92.468  update authors
updating_author<- read.csv("updating_gender_bipoc_data.csv") %>% 
  mutate(author_full_names = author_full_names) %>% 
  select(author_full_names,doi) 

# Merge the above two author datasets into a new author dataset.
author<- author %>% 
  bind_rows(updating_author)

# Perform similar cleaning and format transformation operations on the citation data within it.
reference<- author %>%
  separate_rows(cited_references, sep = "; ") %>% 
  mutate(reference = str_extract(cited_references, "(?<=DOI ).*"),
         reference = str_replace_all(reference, "\\[|\\]", " "),
         reference = str_replace(reference, ".*DOI\\s+", "DOI "),
         reference = str_replace(reference, ".*,\\s+", ", "),
         reference = str_replace(reference, "^DOI ", ""), 
         reference = str_replace_all(reference, " ", ""),
         reference = str_replace_all(reference, ",", ""),
         reference = str_replace(reference, "https://doi.org/", ""),     
         reference = str_replace(reference, "dx.doi.org/", "")
)

# Delete the no longer needed author and updating_author temporary variables.
rm(author)
rm(updating_author)

reference$reference <- gsub("^/", "", reference$reference)

reference<- reference %>%
  mutate(reference = ifelse(reference == "PatentNo.453376", "10.1101/2021.07.22.453376", reference)) %>% 
  filter(!is.na(reference)) %>% 
  select(author_full_names,doi,reference)

# Calculate the list of authors corresponding to each DOI for subsequent self - citation judgment.
# The dataset authors_per_doi contains 2710 .
authors_per_doi <- reference %>%
  group_by(doi) %>%
  summarise(authors = list(unique(author_full_names)))

#The dataset self_citations contains 1326
self_citations <- reference %>%
  left_join(authors_per_doi, by = c("reference" = "doi")) %>%
  rowwise() %>%
  mutate(is_self_citation = any(author_full_names %in% authors)) %>%
  filter(is_self_citation) %>%
  select(doi, reference, author_full_names)

# The dataset reference_info contains 157385 
reference_info<- read.csv("updating_reference_data.csv")%>% 
  select(doi, reference, publication_year) %>% 
  filter(!is.na(reference)) %>% 
  glimpse()

# The dataset full_data contains 9323
full_data<- read.csv("updating_full_data.csv") %>% 
  select(-author_full_names, -cited_count) %>% 
  rename(reference = doi,
         reference_year = publication_year) %>% 
   mutate(
    first_author_gender_bipoc = ifelse(first_author_gender_bipoc == 0, "00", 
                                       ifelse(first_author_gender_bipoc == 1, "01", as.character(first_author_gender_bipoc))),
    last_author_gender_bipoc = ifelse(last_author_gender_bipoc == 0, "00", 
                                      ifelse(last_author_gender_bipoc == 1, "01", as.character(last_author_gender_bipoc))),
    corresponding_author_gender_bipoc = ifelse(corresponding_author_gender_bipoc == 0, "00", 
                                               ifelse(corresponding_author_gender_bipoc == 1, "01", as.character(corresponding_author_gender_bipoc)))
  )
```

```{r}
# Remove self citation data
no_self_citation <- reference_info %>%
  anti_join(self_citations, by = c("doi", "reference"))

# count the number of times each citation is cited.
merged_doi <- no_self_citation %>%
  left_join(full_data, by = "reference") %>%
  group_by(reference) %>%
  mutate(cited_count = n()) %>%
  ungroup()

# The dataset matched_doi contains 3229
matched_doi <- merged_doi %>%
  filter(!is.na(single_author)) %>% 
  rename(cited_doi = reference) %>% glimpse()
```

```{r}
#statistics according to the gender and race of the first author.
cited_probability <- matched_doi %>%
  group_by(first_author_gender_bipoc) %>%
  summarize(
    total_papers = n(),                       
    cited_papers = sum(cited_count > 0),          
    cited_probability = mean(cited_count > 0)     
  )
```


```{r}
write.csv(matched_doi, file = "updating_cleaned_reference.csv", row.names = FALSE)
```
