---
title: "article_clean"
author: "Shiyu Yang"
date: "2024-11-05"
output: html_document
---

# This is step 4 in data cleaning

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# Read data
```{r}
# 2,721 publications in JoCN
raw_jocn <- read.csv("cleaned_jocn.csv") %>% 
  mutate(journal = "jocn") 

# 2,980 publications in Nature Neuroscience
raw_nature_neuroscience <- read.csv("cleaned_nature_neuro.csv") %>% 
  mutate(journal = "nature_neuroscience") 

# 4,249 publications in Brain
raw_brain <- read.csv("cleaned_brain.csv") %>% 
  mutate(journal = "brain") 

# Total of 9,426 publications
raw_data<- raw_jocn %>% 
  bind_rows(raw_nature_neuroscience)%>% 
  bind_rows(raw_brain)%>%
  filter(!is.na(reprint_addresses)) %>%   
  filter(reprint_addresses!="") %>% 
  glimpse()

# Removed raw datasets
rm(raw_jocn)
rm(raw_nature_neuroscience)
rm(raw_brain)

# Total of 9,927 publications
#write.csv(raw_data, file = "updating_raw_article_data.csv", row.names = FALSE)
```

# Prepare for affiliation category
```{r}
### Remember to update this when adding new journal

# Manual cleaned for country, continent, and economies
country_to_continent <- c(
  "South Korea"     = "Asia",
  "Peoples R China" = "Asia",
  "USA"             = "North America",
  "Germany"         = "Europe",
  "Belgium"         = "Europe",
  "Netherlands"     = "Europe",
  "Canada"          = "North America",
  "Switzerland"     = "Europe",
  "England"         = "Europe",
  "Israel"          = "Asia",
  "France"          = "Europe",
  "Singapore"       = "Asia",
  "Italy"           = "Europe",
  "Spain"           = "Europe",
  "Japan"           = "Asia",
  "Austria"         = "Europe",
  "Poland"          = "Europe",
  "Australia"       = "Australia",
  "Portugal"        = "Europe",
  "Norway"          = "Europe",
  "Finland"         = "Europe",
  "Scotland"        = "Europe",
  "North Ireland"   = "Europe",
  "Brazil"          = "South America",
  "New Zealand"     = "Australia",
  "Wales"           = "Europe",
  "Luxembourg"      = "Europe",
  "Sweden"          = "Europe",
  "Taiwan"          = "Asia",
  "Iran"            = "Asia",
  "Bulgaria"        = "Europe",
  "Denmark"         = "Europe",
  "Ireland"         = "Europe",
  "Argentina"       = "South America",
  "Cyprus"          = "Asia",
  "Saudi Arabia"    = "Asia",
  "Turkey"          = "Asia",
  "Cuba"            = "North America",
  "Hungary"         = "Europe",
  "India"           = "Asia",
  "U Arab Emirates" = "Asia",
  "Russia"          = "Europe",
  "Mexico"          = "South America",
  "Slovenia"        = "Europe",
  "Chile"           = "South America",
  "South Africa"    = "Africa",
  "Kenya"           = "Africa",
  "Malawi"          = "Africa",
  "Thailand"        = "Asia",
  "Greece"          = "Europe",
  "Egypt"           = "Africa",
  "Czech Republic"  = "Europe",
  "Kuwait"          = "Asia",
  "Malaysia"        = "Asia",
  "Tunisia"         = "Africa",
  "Malta"           = "Europe",
  "Iceland"         = "Europe",
  "Lithuania"       = "Europe"
)


# Advanced Economies information are from World Economic Outlook
#https://www.imf.org/en/Publications/WEO/weo-database/2023/April/groups-and-aggregates
developed_eco <- c(
  "USA" = 1,
  "Germany" = 1,
  "Belgium" = 1,
  "Netherlands" = 1,
  "Canada" = 1,
  "Switzerland" = 1,
  "England" = 1,
  "Israel" = 1,
  "France" = 1,
  "Singapore" = 1,
  "Italy" = 1,
  "Spain" = 1,
  "Japan" = 1,
  "Austria" = 1,
  "Poland" = 1,
  "Australia" = 1,
  "Portugal" = 1,
  "Norway" = 1,
  "Finland" = 1,
  "Scotland" = 1,
  "North Ireland" = 1,
  "Luxembourg" = 1,
  "Sweden" = 1,
  "Taiwan" = 1,
  "South Korea" = 1,
  "Wales" = 1,
  "New Zealand" = 1,
  "Denmark" = 1,
  "Ireland" = 1,
  "Cyprus" = 1,
  "Russia" = 1,
  "Slovenia" = 1,
  "Greece" = 1,
  "Czech Republic" = 1
)
```


# Data wrangling on variables
```{r} 
cleaned_data<- raw_data %>% 
  mutate(corresponding_author = str_extract(reprint_addresses, "^[^,]+"),
         first_author = str_extract(author_full_names, "^[^;]+"),
         last_author = str_extract(author_full_names, "[^;]+$"),
         last_author = str_trim(last_author, side = "both"),
         single_author = ifelse(str_count(author_full_names, ";") == 0, 1, 0),
         fund = ifelse(!is.na(funding_orgs) & funding_orgs != "", 1, 0),
         country = str_extract(reprint_addresses, "[^,]+$"),
         country = str_remove(country, "\\.$"),
         country = str_trim(country, side = "both"),
         country = str_replace(country, ".*USA.*", "USA"),
         affiliation_con = country_to_continent[country],
         affiliation_dev = developed_eco[country],
         affiliation_us = ifelse(country == "USA", 1, 0),
         author_count = str_count(author_full_names, ";") + 1,
         publication_year = 2024 - publication_year) %>% 
  mutate(corresponding_author = str_replace_all(corresponding_author, regex("ö", ignore_case = TRUE), "oe"),
         corresponding_author = str_replace_all(corresponding_author, regex("ó", ignore_case = TRUE), "o"),
         corresponding_author = str_replace_all(corresponding_author, regex("í", ignore_case = TRUE), "i"),
         corresponding_author = str_replace_all(corresponding_author, regex("ä", ignore_case = TRUE), "ae"),
         corresponding_author = str_replace_all(corresponding_author, regex("è", ignore_case = TRUE), "e"),
         corresponding_author = str_replace_all(corresponding_author, regex("ü", ignore_case = TRUE), "ue"),
         corresponding_author = str_replace_all(corresponding_author, regex("á", ignore_case = TRUE), "a"),
         corresponding_author = str_replace_all(corresponding_author, regex("à", ignore_case = TRUE), "a"),
         corresponding_author = str_replace_all(corresponding_author, regex("ñ", ignore_case = TRUE), "n"),
         corresponding_author = str_replace_all(corresponding_author, regex("é", ignore_case = TRUE), "e"),
         corresponding_author = str_to_lower(corresponding_author))
         
cleaned_data$affiliation_dev[is.na(cleaned_data$affiliation_dev)] <- 0
```

# Data clean on gender and bipoc info
```{r}
# Merged gender and BIPOC info of author
names<- read.csv("jocn_name_list.csv") 

names<- read.csv("nature_neuro_name_list.csv") %>% 
  bind_rows(names) 

names<- read.csv("brain_name_list.csv") %>% 
  bind_rows(names) 

first_author_names<- names%>% 
  mutate(first_author_last_name = str_to_lower(last_name)) %>%
  select(full_name, first_author_last_name) 

last_author_names<- names%>% 
  mutate(last_author_last_name = str_to_lower(last_name)) %>%
  select(full_name, last_author_last_name) 

merged_data<- cleaned_data %>%
  left_join(first_author_names, by = c("first_author" = "full_name")) %>% 
  left_join(last_author_names, by = c("last_author" = "full_name")) %>% 
  distinct()

adjusted_data <- merged_data %>%
  mutate(
    both_match = corresponding_author == first_author_last_name & 
                 corresponding_author == last_author_last_name &
                 first_author != last_author,  
    none_match = corresponding_author != first_author_last_name & 
                 corresponding_author != last_author_last_name,
    corresponding_author = if_else(
      both_match,
      paste(first_author, last_author, sep = " / "),
      if_else(
        corresponding_author == first_author_last_name,
        first_author,
        if_else(
          corresponding_author == last_author_last_name,
          last_author,
          corresponding_author
        )
      )
    )
  )

#Completion of missing doi
adjusted_data <- adjusted_data %>%
  mutate(doi = ifelse(is.na(doi),
                      paste0("NA_", sprintf("%03d", row_number())),
                      doi))

# Check first and last author share the same last name
both_match_rows <- adjusted_data %>%
  filter(both_match)

# Total of 31 articles has the same last name for both first and last author

# Check corresponding author is not either first author or last author
none_match_rows <- adjusted_data %>%
  filter(none_match)

# Total of 812 rows returned, however some of them were due to the format of name. I will manually correct the name for those author.
# Additionally 20 author was not matched due to single author

manual_clean_data <- adjusted_data %>%
  mutate(corresponding_author = ifelse(doi == "10.1162/jocn.2008.21183", "Johnson, Matthew R.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn.2009.21370", "Sanford, Anthony J.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_00085", "Park, Joonkoo", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01607", "Irwin, Louis N.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_00823", "Johnson, Matthew R.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_02119", "Damasio, Antonio", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_02086", "Liu, Li", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_00295", "Dolcos, Sanda", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2972", "Ip, Nancy Y.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3572", "Song, Hongjun", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2349", "Li, Chenjian", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3006", "Li, Xiao-Ming", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-021-00944-z", "Lee, Gabsang", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4469", "Smith, Spencer L.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-019-0545-6", "Bennett, Mariko L.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4519", "Shi, Song-Hai", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-020-0635-5", "Wingo, Aliza P.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2474", "Liu, Siqiong June", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2975", "Lee, Junho", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-021-00832-6", "Wingo, Thomas S.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3322", "Li, Bo", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2355", "Wu, Ling-Gang", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awac166", "Lee, Soon Tae", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awaa364", "Jia, Jianping", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab252", "Wang, Hongxing", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aww158", "Araujo, Abelardo Q. C.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awv016", "Wang, Shuu-Jiun", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awx144", "Kim, Jongpil", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz205", "Lee, Jun Sung", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awad045", "Chen, Shih-Pin", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz070", "Xu, Jin", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awr252", "Schmidt, Helena", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awt303", "Grabrucker, Stefanie", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aws352", "Camfield, Carol S.", corresponding_author),
         
         corresponding_author = ifelse(doi == "10.1038/s41593-024-01655-x", "Inglis, George Andrew", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-024-01621-7", "Howells, Henrietta", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-023-01495-1", "Wright, Rebecca", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-024-01687-3", "Mejia, Luis A.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-024-01662-y", "Inglis, George", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-024-01688-2", "Wiseman, Shari", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-024-01581-y", "Wiseman, Shari", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-024-01686-4", "Inglis, George Andrew S.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-024-01583-w", "Wright, Rebecca", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-024-01661-z", "Inglis, George", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-024-01656-w", "Wright, Rebecca", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-024-01622-6", "Inglis, George Andrew S.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-024-01660-0", "Inglis, George", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-024-01632-4", "Floriddia, Elisa", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-024-01582-x", "Welberg, Leonie", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-024-01603-9", "Wright, Rebecca", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-024-01623-5", "Mejia, Luis A.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-024-01601-x", "Welberg, Leonie", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-024-01602-w", "Wiseman, Shari", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-024-01657-9", "Howells, Henrietta", corresponding_author),
         
         corresponding_author = ifelse(doi == "10.1162/jocn_a_02082", "Kosem, Anne", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_00313", "Hoscheidt, Siobhan", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn.2010.21557", "Handel, Barbara F.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01414", "Patai, Eva Zita", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn.2010.21571", "Peng, Dan-ling", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn.2009.21355", "Bocker, Koen B. E.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn.2009.21304", "Gillon Dowens, Margaret", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn.2009.21076", "Dehaene-Lambertz, Ghislaine", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01798", "van Ginkel, Wendy", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_00468", "Baumann, Oliver", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01894", "Li, Zhurong", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01802", "Raykov, Petar P.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01459", "Costa, Tommaso", corresponding_author),
         corresponding_author = ifelse(first_author == "Bogels, Sara", "Bogels, Sara", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_02058", "Trettenbrein, Patrick C.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01338", "Duecker, Felix", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_00180", "Andoni Dunabeitia, Jon", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn.2010.21483", "Sass, Katharina", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn.2010.21489", "Blumstein, Sheila E.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn.2010.21429", "Hanakawa, Takashi", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01819", "Sorensen, Lynn K. A.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01681", "Roelfsema, Pieter R.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01175", "Akyurek, Elkan G.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_00983", "Muri, Rene M.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_00897", "Zhang, Jue", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn.2010.21448", "Maquet, Pierre", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_00963", "Chu, Mingyuan", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn.2009.21350", "Oztekin, Ilke", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01664", "Chen, Lihong", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_00633", "Rubin, David C.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn.2009.21202", "Deco, Gustavo", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_02090", "Chen, Qi", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01865", "Zhang, Meng", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01393", "Brosnan, Meadhbh B.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01400", "Stormer, Viola S.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_00670", "Meltzer, Jed A.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01816", "Stock, Ann-Kathrin", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn.2009.21141", "Peng, Danling", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01592", "Polti, Ignacio", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_00199", "Khader, Patrick H.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn.2009.21259", "Albert, Neil B.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_02118", "Pesci, Ugo Giulio", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01793", "Li, Mingyang", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn.2009.21269", "Bogels, Sara", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01415", "Rademaker, Rosanne L.", corresponding_author),
         corresponding_author = ifelse(first_author == "Sorqvist, Patrik", "Sorqvist, Patrik", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01469", "Maki-Marttunen, Veronica", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01579", "Kosem, Anne", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01484", "Feldmann-Wustefeld, Tobias", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn.2009.21236", "Jansen, Petra", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01910", "Guo, Xiuyan", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01502", "Feldmann-Wustefeld, Tobias", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01563", "Hagoort, Peter", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_00651", "Ramsey, Richard", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn.2010.21594", "Adenzato, Mauro", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_00478", "Soderqvist, Stina", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01913", "Tao, Sha", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_00911", "Olivier, Etienne", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01715", "Dezfouli, Mohsen Parto", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_00874", "Luttke, Claudia S.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn.2009.21200", "Blumstein, Sheila E.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01864", "Morton, Neal W.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01751", "Knoch, Daria", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_00131", "Cui, Cailian", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn.2009.21376", "Sarkamo, Teppo", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn.2008.21146", "Oztekin, Ilke", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01664", "Chen, Lihong", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_00633", "Rubin, David C.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn.2009.21202", "Deco, Gustavo", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_02090", "Shen, Lu", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01865", "Zhang, Meng", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01393", "Brosnan, Meadhbh B.", corresponding_author),

         corresponding_author = ifelse(doi == "10.1162/jocn_a_01400", "Stormer, Viola S.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_00670", "Meltzer, Jed A.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01816", "Stock, Ann-Kathrin", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn.2009.21141", "Peng, Danling", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01592", "Polti, Ignacio", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_00199", "Khader, Patrick H.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn.2009.21259", "Albert, Neil B.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_02118", "Pesci, Ugo Giulio", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01793", "Li, Xiaoqing", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn.2009.21269", "Bogels, Sara", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01415", "Rademaker, Rosanne L.", corresponding_author),
         doi = ifelse(author_full_names == "Sorqvist, Patrik; Stenfelt, Stefan; Ronnberg, Jerker", "10.1162/jocn_a_00275", doi),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_00275", "Sorqvist, Patrik", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01469", "Maki-Marttunen", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01579", "Kosem, Anne", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01484", "Feldmann-Wustefeld", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01910", "Guo, Xiuyan", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn.2009.21236", "Jansen, Petra", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01502", "Feldmann-Wustefeld", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01563", "Hagoort, Peter", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_00651", "Ramsey, Richard", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn.2010.21594", "Adenzato, Mauro", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_00478", "Soderqvist, Stina", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01913", "Tao, Sha", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_00911", "Olivier, Etienne", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01715", "Dezfouli, Mohsen Parto", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_00874", "Luttke, Claudia S.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn.2009.21200", "Blumstein, Sheila E.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01864", "Morton, Neal W.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_01751", "Knoch, Daria", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn_a_00131", "Cui, Cailian", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn.2009.21376", "Sarkamo, Teppo", corresponding_author),
         corresponding_author = ifelse(doi == "10.1162/jocn.2008.21146", "Oztekin, Ilke", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4082", "Xu, Tonghui", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3545", "Ferron, Sacri R.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3459", "Pelkey, Kenneth A.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3229", "Mamassian, Pascal", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-024-01620-8", "Krizhanovsky, Valery", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-023-01366-9", "Stassart, Ruth M.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-022-01240-0", "Monroe, Kathryn M.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-022-01013-9", "Dorostkar, Mario M.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-021-00975-6", "Wu, Long-Jun", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-020-00776-3", "Druckmann, Shaul", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-019-0431-2", "Roska, Botond", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-018-0288-9", "Wisden, William", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3975", "Schuman, Erin M.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3712", "Costa, Rui M.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3107", "Farrant, Mark", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3040", "Aruga, Jun", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2609", "Foldy, Csaba", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-022-01021-9", "Witten, Ilana B.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-020-00740-1", "Brennand, Kristen J.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-019-0433-0", "Holtzman, David M.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4534", "Park, John K.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3946", "Fishell, Gord", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-024-01638-y", "Franks, Nicholas P.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-024-01570-1", "Horn, Andreas", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-023-01396-3", "Kiehn, Ole", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-023-01356-x", "Habib, Naomi", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-022-01183-6", "Simons, Mikael", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-020-00787-0", "Jaffe, Andrew E.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-018-0285-z", "Yu, Shi-Cang", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-017-0018-8", "Boyden, Edward S.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4632", "Mostafavi, Sara", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4593", "Gradinaru, Viviana", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4581", "Jayaraman, Vivek", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4568", "Kellendonk, Christoph", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3990", "Cull-Candy, Stuart G.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3404", "Binshtok, Alexander M.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3005", "Mei, Lin", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2934", "Cirelli, Chiara", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-024-01658-8", "Myers, Richard M.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-022-01033-5", "Massey, Thomas H.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-021-00913-6", "Jin, Peng", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-020-0618-6", "Guilliams, Martin", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-019-0501-5", "Cruchaga, Carlos", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-019-0442-z", "Albeanu, Dinu F.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-018-0329-4", "Schaffer, Chris B.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-018-0154-9", "Bennett, David A.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4499", "Turk-Browne, Nicholas B.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3479", "Zou, Sige", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3246", "Tsien, Roger Y.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3062", "Woertge, Simone", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2416", "Hevner, Robert F.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-023-01259-x", "Liston, Conor", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-019-0481-5", "Zamponi, Gerald W.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4398", "Ikram, M. Arfan", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-019-0417-0", "Zeng, Hongkui", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-017-0017-9", "Willsey, A. Jeremy", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-021-00952-z", "Ma, Minghong", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4631", "Jucker, Mathias", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2338", "Choquet, Daniel", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-023-01452-y", "McVicker, Graham", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-023-01406-4", "Lee, Sung Joong", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-019-0492-2", "Yu, Guoqiang", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-019-0445-9", "Wu, Shengxi", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3789", "Lu, Jun", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3628", "McMahon, Stephen B.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3510", "Rich, Jeremy N.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3218", "Amdam, Gro V.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3175", "Albert, Joerg T.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2549", "Wickman, Kevin", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4454", "Lewin, Gary R.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4256", "Horvath, Steve", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2974", "Venance, Laurent", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-024-01649-9", "Golden, Sam A.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-023-01361-0", "Taroncher-Oldenburg, Gaspar", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-022-01041-5", "Yan, Jun", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-021-00889-3", "Olveczky, Bence P.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-018-0193-2", "Zipp, Frauke", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3480", "Marnett, Lawrence J.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3346", "Trauner, Dirk", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2337", "Wiener, Sidney I.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-024-01666-8", "Franklin, Robin J. M.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-024-01595-6", "Du, Jiu-Lin", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-023-01487-1", "Kipnis, Jonathan", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-023-01345-0", "Ding, Jun B.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-022-01182-7", "Paquola, Apua C. M.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-022-01108-3", "Odoardi, Francesca", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-021-00811-x", "Zhang, Zhi", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-020-0650-6", "Lewcock, Joseph W.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-019-0389-0", "Frankland, Paul W.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-019-0364-9", "Fontanini, A.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-018-0187-0", "Hoffman, Gabriel E.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3606", "Duff, Karen E.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3484", "Freimer, Nelson B.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3258", "Destexhe, Alain", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2414", "Benowitz, Larry I.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-022-01251-x", "Wang, Xiao", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-022-01194-3", "Olveczky, Bence P.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-020-00757-6", "Saher, Gesine", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-019-0524-y", "Ma, Lan", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-019-0498-9", "Dupuis, Luc", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2295", "Fettiplace, Robert", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-024-01598-3", "Korotkova, Tatiana", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4520", "Uchida, Naoshige", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4321", "Nave, Klaus-Armin", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4141", "Lau, Brian", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3995", "Crawford, Gregory E.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3289", "LaMotte, Robert H.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2985", "Jentsch, Thomas J.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-020-00754-9", "Lisberger, Stephen G.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-020-0607-9", "Zlatic, Marta", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-019-0578-x", "Maher, Brady J.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-019-0508-y", "Luthi, Andreas", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-018-0324-9", "Wang, Guixue", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4449", "Muller, Ulrich", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2994", "Snyder, Solomon H.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2736", "Layé, Sophie", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2702", "Ffrench-Constant, Charles", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2481", "Mulle, Christophe", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-023-01506-1", "Burgalossi, Andrea", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-023-01315-6", "Gan, Li", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-021-00894-6", "Vyazovskiy, Vladyslav V.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3003", "Sabatini, Bernardo L.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2432", "Heppner, Frank L.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-023-01430-4", "Wisden, William", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-023-01367-8", "Meletis, Konstantinos", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-022-01218-y", "Parker, T. C.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-022-01060-2", "Nahrendorf, Matthias", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-021-00842-4", "Zador, Anthony M.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-019-0358-7", "Ginty, David D.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-018-0297-8", "Feinberg, Andrew P.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4634", "Losonczy, Attila", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3780", "Zhong, Haining", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-023-01306-7", "Losonczy, Attila", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-022-01202-6", "Cardin, Jessica A.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-022-01136-z", "Zhen, Zonglei", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-020-0646-2", "Magee, Jeffrey C.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-018-0256-4", "Yan, Junan", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4265", "Guler, Ali D.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4208", "Wang, Hao", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2976", "Schulz, Joachim G.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2495", "Deisseroth, Karl", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2452", "Zufall, Frank", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-023-01432-2", "Kawakami, Naoto", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-022-01168-5", "Bathellier, Brice", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-021-00837-1", "Ji, Minjun", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4613", "Brody, Carlos D.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3831", "Anderson, Kathryn V.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2880", "Feng, Guoping", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4010", "Amir, Shimon", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3737", "Lowell, Bradford B.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3538", "Pelkey, Kenneth A.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3077", "Magee, Jeffrey C.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3553", "Wechsler-Reya, Robert J.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3427", "Roska, Botond", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3230", "Cleveland, Don W.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2497", "Ding, Xinxin", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-022-01140-3", "Gandhi, Sonia", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-019-0582-1", "Chan, Jonah R.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4193", "Miller, Stephen D.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2832", "Maylie, J", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-022-01073-x", "Liu, Sheng", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-022-01029-1", "Kipnis, Jonathan", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-021-00924-3", "Moron, Jose A.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-019-0565-2", "Owen, Michael J.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-019-0425-0", "Distel, Ben", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3891", "Munch, Thomas A.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3357", "Rothstein, Jeffrey D.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2673", "Murthy, Venkatesh N.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2646", "Lovell-Badge, Robin", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2300", "Chen, Jian-Guo", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-024-01678-4", "Goritz, Christian", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-024-01594-7", "Carey, Megan R.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-023-01316-5", "Castren, Eero", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-022-01104-7", "Schwartz, Michal", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-021-01001-5", "Lynch, Gary", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4378", "Spitale, Robert C.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2749", "Deisseroth, Karl", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2382", "Rao, Yi", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2247", "Hegemann, Peter", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-022-01062-0", "Xu, Yong", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-022-01020-w", "Kreiman, Gabriel", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-021-00960-z", "Prevot, Vincent", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-020-00771-8", "Banks, William A.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-020-0592-z", "Hashimoto-Torii, Kazue", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-019-0452-x", "Engert, Florian", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-019-0423-2", "Stahlberg, Henning", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4532", "Thompson, Leslie M.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3925", "Grabenhorst, Fabian", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3901", "Groc, Laurent", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3142", "Core, Nathalie", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2409", "Huylebroeck, Danny", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2362", "Garner, Craig C.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-022-01129-y", "Zhou, Yu-Dong", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-020-0597-7", "Zou, Hongyan", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4643", "von Andrian, Ulrich H.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4257", "Lin, Da-Ting", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3485", "Maravall, Miguel", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-023-01436-y", "Chen, Yelin", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-022-01193-4", "Carmignoto, Giorgio", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-020-0704-9", "Pacureanu, Alexandra", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-018-0278-y", "Jefferys, John G. R.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-024-01689-1", "Daw, Nathaniel D.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-021-00849-x", "Rogers, John A.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-020-00794-1", "Kriegstein, Arnold R.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-021-00804-w", "Dupret, David", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3801", "Ryten, Mina", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3323", "Tranel, Daniel", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2327", "Ehlers, Michael D.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-019-0489-x", "Courchesne, Eric", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4654", "Giocomo, Lisa M.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3036", "Poo, Mu-ming", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2312", "Loken, Line S.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-023-01431-3", "Olveczky, Bence P.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-023-01435-z", "Becher, Burkhard", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-021-00876-8", "Nestadt, Gerald", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-021-00840-6", "Svoboda, Karel", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4612", "Ming, Guo-Li", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4544", "Rico, Beatriz", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4310", "Ulanovsky, Nachum", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4074", "Menendez de la Prida, Liset", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3670", "Schaefer, Anne", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3451", "Caspary, Tamara", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2282", "Piazza, Pier Vincenzo", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-024-01671-x", "Schutt, Heiko H.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-022-01161-y", "Yehuda, Rachel", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-018-0247-5", "Fitzpatrick, David", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4604", "El-Khamisy, Sherif F.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4549", "Wang, Yun", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4376", "Ernfors, Patrik", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4337", "Weinberger, Daniel R.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3281", "Sereda, Michael W.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2844", "Paoletti, Pierre", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2390", "Grisar, Thierry", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-023-01484-4", "Schroeder, Gunnar F.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-021-00814-8", "Nestler, Eric J.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-020-0684-9", "Cui, Guohong", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-018-0141-1", "Ernfors, Patrik", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4648", "Lopes, Luisa V.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4495", "Tsai, Linus T.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3052", "Hisamoto, Naoki", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3035", "Crochet, Sylvain", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2622", "Pierani, Alain", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2616", "Lichtman, Aron H.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-024-01664-w", "Friedel, Roland H.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-022-01181-8", "Deppmann, Christopher D.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-021-00908-3", "Koellinger, Philipp D.", corresponding_author),
         # Missing due to missing doi
         corresponding_author = ifelse(first_author == "Bogels, Sara", "Bogels, Sara", corresponding_author),
         corresponding_author = ifelse(first_author == "Nandam, Sanjay", "Nandam, Sanjay", corresponding_author),
         corresponding_author = ifelse(first_author == "Kuehn, Simone", "Kuehn, Simone", corresponding_author),
         corresponding_author = ifelse(first_author == "Kraemer, Ulrike M.", "Kraemer, Ulrike M.", corresponding_author),
         corresponding_author = ifelse(last_author == "Zhou, Yong-Di", "Zhou, Yong-Di", corresponding_author),
         corresponding_author = ifelse(first_author == "Haeberling, Isabelle S.", "Haeberling, Isabelle S.", corresponding_author),
         corresponding_author = ifelse(first_author == "Verleger, Rolf", "Verleger, Rolf", corresponding_author),
         corresponding_author = ifelse(first_author == "Stoermer, Viola S.", "Stoermer, Viola S.", corresponding_author),
         corresponding_author = ifelse(first_author == "Jaencke, Lutz", "Jaencke, Lutz", corresponding_author),
         corresponding_author = ifelse(first_author == "Kranjec, Alexander", "Kranjec, Alexander", corresponding_author),
         corresponding_author = ifelse(first_author == "Churchland, Anne K.", "Churchland, Anne K.", corresponding_author),
         corresponding_author = ifelse(first_author == "Jorfi, Mehdi", "Jorfi, Mehdi", corresponding_author),
         corresponding_author = ifelse(first_author == "Vogels, Tim P.", "Vogels, Tim P.", corresponding_author),
         corresponding_author = ifelse(first_author == "Abbott, L. F.", "Abbott, L. F.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awad122", "Misu, Tatsuro", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awac275", "Chari, Aswin", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab419", "Reich, Daniel S.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab354", "Pei, Zhong", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab005", "Poewe, Werner", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awu356", "Reilly, Mary M.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awt353", "Rodriguez de Cordoba, Santiago", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awt344", "Schurmans, Stephane", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aws161", "Houlden, Henry", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awq325", "Liu, Yang", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awp337", "Gallyas, Ferenc, Jr.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awp278", "Weinstock-Guttman, B ", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awad336", "Kullmann, Dimitri M.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab395", "Lochmueller, Hanns", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awaa133", "Ittner, Lars M.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz153", "Zhang, Hong-Qi", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aww257", "Laporte, Jocelyn", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awq287", "Baas, Frank", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awq160", "Elvevag, Brita", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awae125", "George Jr, Alfred L.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awad315", "Nalini, Atchayaram", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awad282", "Capsoni, Simona", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab113", "Dib-Hajj, Sulayman D.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awv192", "Allenbach, Yves", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awu002", "Sidransky, Ellen", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aws174", "Sidransky, Ellen", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awr149", "Bjorklund, Anders", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awp163", "Meuth, Sven G.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awad086", "Nilsen, Hilde L.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awac474", "Nij Bijvank, Jenny A.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awac273", "de la Pena, Elvira", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awy289", "Mathews, Paul M.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awx005", "Fleming, Angeleen", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aws136", "Solowij, Nadia", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awq193", "Mima, Tatsuya", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awp298", "Stuve, Olaf", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awp077", "Hodges, J. R.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awad211", "Polania, Rafael", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awad098", "Cox, James J.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab313", "Wolf, Nicole I.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab056", "Taniguchi-Ikeda, Mariko", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awaa022", "Staats, Kim A", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz370", "Muhlebner, Angelika", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz379", "Chung, Brian H. Y.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awv334", "Zokaei, Nahid", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awr079", "Collinge, John", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awq083", "Oldfors, Anders", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awp069", "Ballard, Clive G.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awp110", "Kakita, Akiyoshi", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awn262", "de Haan, W.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awac341", "Hu, Qingmao", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awac073", "Schwartz, Theodore H.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awx179", "Luczak, Artur", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awx058", "Lee, Yi-Chung", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aww322", "Sander, Josemir W.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awv224", "Martinez, Aurora", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awv204", "Meiner, Vardiella", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awae029", "Feng, Hua", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab475", "Lepousez, Gabriel", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awaa174", "Lequin, Maarten H.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz406", "Li, Xingang", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz419", "Patani, Rickie", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awy197", "Makinen, Ville-Petteri", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awy064", "de Oliveira-Souza, Ricardo", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awv360", "Bliss, Tonya M.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aws070", "van der Knaap, Majro S.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awaa116", "Kocsis, Jeffery D.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awaa016", "Dib-Hajj, Sulayman D.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz195", "Zuberi, Sameer M.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awx300", "Greenlee, Jeremy D.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aww116", "O'Brien, Terence J.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aws288", "Bloem, Bastiaan R.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awq120", "Shinotoh, Hitoshi", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awae011", "Rojas-Garcia, Ricard", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awad321", "Wang, Wei", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awad109", "Ruocco, Maria Grazia", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab440", "Luk, Kelvin C.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab200", "Park, In Young", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab160", "Zhou, Yun", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awaa336", "Sharp, David J.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awaa057", "Guo, Qihao", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz380", "Takahashi, Ryosuke", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awy299", "van Ballegoij, Wouter J. C.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aww217", "Terwindt, Gisela M.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awv208", "Schevon, Catherine A.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aws242", "Stagg, Charlotte J.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awp010", "Wardlaw, Joanna M.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awad424", "Sanderson, Nicholas S. R.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awad245", "Nadif Kasri, Nael", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awad235", "Huebner, Christian A.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awac245", "Katsumi, Yuta", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab250", "Hendrix, Sven", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab130", "Elena Avale, Maria", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz303", "Bernabei, John M.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz276", "McCcoy, Bronagh", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz196", "Rizzi, Michele", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz176", "BjOrklund, Tomas", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awx198", "Bennett, Hugh P. J.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awx236", "Lerche, Holger", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awv188", "Ryu, Hoon", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awv108", "Magerl, Walter", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awv181", "Skillback, Tobias", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awr261", "Nijtmans, Leo G. J.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awq324", "Bloem, Bastiaan R.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awad410", "Leblanc, Pascal", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awad402", "Avesani, Paolo", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awad256", "Cabrera-Serrano, Macarena", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab312", "Staley, Kevin J.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab102", "Misu, Tatsuro", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awaa318", "Boulinguez, Philippe", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awaa208", "Dib-Hajj, Sulayman D.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awaa201", "Xiao, Qin", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awx272", "van Zundert, Brigitte", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aww330", "Klatzmann, David", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aww173", "Butzkueven, Helmut", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aww038", "Geppetti, Pierangelo", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awq353", "Carpenter, Keri L. H.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awq184", "Dolors Soler, Maria", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awac116", "Houlden, Henry", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab445", "Hanna, Michael G.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz151", "Xu, Xiang-Min", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz202", "Qi, Songtao", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awy355", "Arshad, Qadeer", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awy247", "Vezzani, Annamaria", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awx377", "Van Maldergem, Lionel", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awu165", "Wissinger, Bernd", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awq091", "Takeda, Atsushi", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awac364", "Alkuraya, Fowzan S.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awac024", "Ramirez, Alfredo", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awaa399", "Scholl, Michael", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awaa008", "Cappelletti, Graziella", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz326", "Guerrini, Renzo", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awy285", "Durr, Alexandra", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awy009", "Zhao, Jing", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aww318", "Crosby, Andrew H.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aww068", "Politi, Letterio S.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aws317", "Kraemer, Kenneth H.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awp280", "Boeve, Bradley", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awp045", "Lonnqvist, Tuula", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awad085", "Miserocchi, Anna", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awad048", "Specchio, Nicola", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab257", "Berardelli, Alfredo", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awaa033", "Cope, Thomas E.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aws243", "McLaurin, JoAnne", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awad322", "Spindler, Lennart R. B.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awad050", "Tucci, Arianna", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awad042", "Jack Jr, Clifford R.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awac455", "Beck, Heinz", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awac388", "Halai, Ajay D.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab396", "Marques Jr, Wilson", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awac011", "Langenhan, Tobias", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab273", "Destrieux, Christophe", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awaa459", "Kaya, Namik", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awaa045", "Lignani, Gabriele", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz377", "Durr, Alexandra", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz189", "Ling, Helen", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz100", "Colin, Morvane", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awy351", "Gao, Zhihua", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aww251", "DiAntonio, Aaron", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aww180", "De Jonghe, Peter", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awv383", "Bao, Ai-Min", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awu044", "Karnath, Hans-Otto", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awt048", "Collinge, John", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awae180", "Sjoberg, Rickard L.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awac258", "Kapogiannis, Dimitrios", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab379", "Cerri, Gabriella", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awy071", "Walker, Matthew C.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aww295", "Falik Zaccai, Tzipora C.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awr152", "Tononi, Giulio", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awad007", "Bernabei, John M.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awac444", "Slama, Abdelhamid", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab101", "Flucher, Bernhard E.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awaa151", "Freund, Christian", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz174", "Caboche, Jocelyne", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awv366", "Chiaretti, Antonio", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awr064", "Naatanen, Risto", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awr028", "Pavese, Nicola", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awad274", "Yan, Chuanzhu", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awad052", "Cirrito, John R.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awac395", "Amati-Bonneau, Patrizia", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awac135", "Liao, Yi-Chu", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab264", "Brown, Peter", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab129", "Scholtzova, Henrieta", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awaa426", "Zhou, Yan", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz269", "Gelinas, Jennifer N.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awy323", "Kaufmann, Walter E.", corresponding_author),
         corresponding_author = ifelse(doi == "	
10.1093/brain/awy324", "Wagnon, Jacy L.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awy283", "Hanna, Michael G.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awx094", "Spinazzola, Antonella", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aww223", "Volkmann, Jens", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aww130", "Lochmuller, Hanns", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aww039", "Galino, Jorge", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awt246", "Mattle, Heinrich P.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awr005", "Schiff, Nicholas D.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awq350", "O'Connor, Kevin C.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awad146", "van der Knaap, Marjo S.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awac404", "Bauer, Jan", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awac087", "Cruz Rodriguez-Oroz, Maria", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab237", "Hong, Tao", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awaa251", "Fonderico, Mattia", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awaa163", "Schmid, Annina B.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awaa168", "Engel, Tobias", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz374", "Christodoulou, John", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awy290", "de Tayrac, Marie", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awy135", "Alkuraya, Fowzan S.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awy020", "Melki, Judith", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aww259", "Kim, Dong-Eog", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aww100", "Apkarian, A. Vania", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aww036", "Aebischer, Patrick", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awt195", "Ouchi, Yasuomi", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awr042", "Hayflick, Susan J.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awq185", "Keage, Hannah A. D.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awp094", "Keri, Szabolcs", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awac360", "Li, Chao", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab209", "Hu, Hao", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awaa090", "Cui, Mei", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz361", "Bassett, Danielle S.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz058", "Lee, Eun-Ho", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aww307", "Schuele, Rebecca", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aws213", "Scott, Rod C.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awae113", "Blum, David", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awae026", "Bjorklund, Anders", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awac497", "Hallermann, Stefan", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awac402", "Delague, Valerie", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab409", "Bellen, Hugo J.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awac138", "Wu, Yu-Chien", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab401", "Kwan, Patrick", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab052", "Guerrini, Renzo", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz372", "Tang, Bei-Sha", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz022", "Gaudilliere, Dyani", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awx366", "Ma, Xiaohong", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awx132", "Holzenberger, Martin", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awv392", "Bertini, Enrico", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awv257", "Vincent, Angela", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aws126", "Nishio, Yoshiyuki", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awq371", "Hedstrom, Anna Karin", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awp314", "Bjorklund, Tomas", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awn305", "Bjorklund, Anders", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awae018", "Holt, Ian J.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awad004", "Zhang, Chencheng", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awac439", "Lin, Jean-Pierre", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awac411", "Wang, Wen-Yuan", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awaa279", "Wu, Ruey-Meei", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awaa111", "Muenchau, Alexander ", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz414", "Vachon-Presseau, Etienne", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz017", "Bar-Or, Amit", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awy198", "Schenck, Annette", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awy034", "Reid, Evan", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awt321", "Turnbull, Doug M.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awt097", "Fisher, Elizabeth M. C.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awr223", "Chen, Huafu", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awad311", "Girn, Manesh", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awac080", "Cruchaga, Carlos", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awaa338", "Massimini, Marcello", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awaa126", "Ling, Helen", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz391", "Verhage, Matthijs", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz217", "Patani, Rickie", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz134", "Wietecha, Linda A.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awy304", "Lemke, Johannes R.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awy177", "Geppetti, Pierangelo", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awv353", "Kerschensteiner, Martin", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awv130", "Kirsch, Heidi E.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awt053", "Uceyler, Nurcan", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aws230", "Hasegawa, Masato", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awr068", "Friedmann, Naama", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awad366", "Zhang, Jiaqiang", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awad058", "Shi, Chang-he", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awac456", "Voon, Valerie", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awac461", "Dowling, James J.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awac069", "Misic, Bratislav", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab316", "Mueller-Vahl, Kirsten R.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awaa102", "Misu, Tatsuro", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz270", "Brochet, Bruno", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz095", "Nicolas, Gael", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awy253", "Geis, Christian", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awy237", "Gillingwater, Thomas H.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aww061", "Martin, Jean-Jacques", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awv350", "Prokisch, Holger", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awv158", "Seeman, Pavel", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awt327", "Hagel, Christian", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aws320", "van der Knaap, Majro S.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awq060", "Silani, Giorgia", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awp229", "Debu, B.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab062", "Ye, Keqiang", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awaa436", "Trattnig, Siegfried", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awaa283", "Wang, Jian", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awy230", "Klein, Christine", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awy059", "Wiste, Heather J.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awx208", "Mombaerts, Peter", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awx129", "Berkovic, Samuel F.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aww215", "Wang, Zhong I.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awr239", "Scott, Rod C.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awq069", "Zhong, Chunjiu", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awp202", "Carpenter, Keri L. H.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awae005", "Cox Jr, Charles S.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awad194", "Grothe, Michel J.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awac473", "Nbrega, Clevio", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awac267", "Zhang, Jintao", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awac128", "Escott-Price, Valentina", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awac061", "Peelaerts, Wouter", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz115", "Tabrizi, Sarah J.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awx093", "Tafti, Mehdi", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awv138", "Stenzel, Werner", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awv063", "Devos, David", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awu095", "Ilvesmaki, Tero", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awac280", "Koenig, Michel", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab470", "Guan, Yuguang", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab125", "Wu, Jinsong", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awaa206", "Knopp, Cordula", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz346", "Hoglund, Kina", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz175", "Guerrini, Renzo", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz078", "Lanznaster, Debora", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awx171", "Scholl, Michael", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awx130", "Terwindt, Gisela M.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awx095", "Ramirez, Alfredo", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aww161", "Ito, Daisuke", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awt023", "Zipp, Frauke", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awr094", "Bliss, Tonya M.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awad403", "Kristensen, Anders S.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awae012", "Nobre, Rui Jorge", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awae015", "Li, Gang", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awad434", "Rubio, Ignacio", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awad084", "Wang, Shan", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab420", "Shaw, Pamela J.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab329", "Di Cristo, Graziella", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab246", "Cogram, Patricia", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab275", "Bonnemann, Carsten G.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab078", "Patani, Rickie", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab219", "Rubboli, Guido", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz295", "Ryten, Mina", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz150", "Epelbaum, Stephane", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awy310", "Linster, Carole L.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awx372", "Sawcer, Stephen", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awx344", "Halliday, Glenda M.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awu230", "Krull, Kevin R.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awr104", "Abramov, Andrey Y.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awr041", "Ben-Ari, Yehezkel", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awq376", "Zheng, Yuan-lin", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awp162", "Ali, Carine", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awad387", "Lignani, Gabriele", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awac123", "Baple, Emma L.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab366", "Patani, Rickie", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab001", "Morgante, Francesca", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz328", "de Almeida, Luis Pereira", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz319", "Gressens, Pierre", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aww018", "Gagnon, Jean-Francois", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awv046", "Cross, Anne H.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aws318", "Evans, Jonathan R.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awq195", "Belfer, Inna", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awp017", "Macdonell, Richard", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awae106", "Li, Lingyong", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awad316", "Puglisi, Guglielmo", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awad280", "Morfini, Gerardo A.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awad064", "Wade-Martins, Richard", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awac244", "Hester, Mark E.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab436", "Peris, Leticia", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awz137", "Arnulf, Isabelle", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awy346", "van Karnebeek, Clara D. M.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awt221", "Shalchi, Zaid", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awp290", "Schachner, Melitta", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awp030", "Raisman, Geoffrey", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awn318", "Al-Shahi Salman, Rustam", corresponding_author),

         corresponding_author = ifelse(doi == "10.1093/brain/awv266", "Abe, Christoph", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3951", "Acsady, Laszlo", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aws196", "Baeckman, Cristina M.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awaa450", "Berenyi, Antal", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aws349", "Bejot, Yannick", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awq215", "Bluemcke, Ingmar", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awt284", "Boennemann, Carsten G.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awn325", "Boennemann, Carsten G.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awu368", "Boennemann, Carsten G.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-023-01323-6", "Boillee, Severine", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-020-00718-z", "Boillee, Severine", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awu312", "Boillee, Severine", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awaa158", "Brueck, Wolfgang", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-021-00854-0", "Bruening, Jens C.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2847", "Bruening, Jens C.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3449", "Bruening, Jens C.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3583", "Bruestle, Oliver", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-018-0290-2", "Boettcher, Chotima", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-024-01633-3", "Burguiere, Eric", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3905", "Buzsaki, Gyoergy", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3304", "Buzsaki, Gyoergy", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2894", "Buzsaki, Gyoergy", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-023-01270-2", "Buzsaki, Gyoergy", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3968", "Buzsaki, Gyoergy", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4543", "Buzsaki, Gyoergy", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4637", "Buzsaki, Gyoergy", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3952", "Buzsaki, Gyoergy", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-021-00797-6", "Buzsaki, Gyoergy", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab076", "Calo, Laura", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-019-0354-y", "Carlen, Marie", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aws134", "Chabardes, Stephan", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awr366", "Chio, Adriano", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awq383", "Chetelat, Gael", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awq187", "Chetelat, Gael", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awx279", "Chetelat, Gael", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awp132", "Chetelat, Gael", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aww159", "Chetelat, Gael", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awq203", "Chetelat, Gael", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab301", "Diaz-Manera, Jordi", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awaa228", "Diaz-Manera, Jordi", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4243", "Deneve, Sophie", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awac384", "Diez-Cirarda, Maria", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awv408", "Dorothee, Guillaume", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awab405", "Duezel, Emrah", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-018-0301-3", "Ertuerk, Ali", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awv311", "Espinos, Carmen", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2437", "Farinas, Isabel", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/aww002", "Floeel, Agnes", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awq135", "Fluegel, Alexander", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3706", "Frisen, Jonas", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2268", "Frisen, Jonas", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awq241", "Frisen, Jonas", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awae041", "Garcia-Cazorla, Angeles", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awad010", "Garcia-Cazorla, Angeles", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awt171", "Gomez-Isla, Teresa", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.4616", "Gonzalez-Maeso, Javier", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3181", "Gonzalez-Maeso, Javier", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-021-00856-y", "Graeff, Johannes", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awac464", "Gruenewald, Anne", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awu213", "Grueninger, Fiona", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.3371", "Goetz, Magdalena", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/nn.2399", "Goetz, Magdalena", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awt348", "Gulyas, Attila I.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awq278", "Guzman, Manuel", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awac276", "Goevert, Felix", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awv246", "Harle, Katia M.", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awx039", "Huebener-Schmid, Jeannette", corresponding_author),
         corresponding_author = ifelse(doi == "10.1038/s41593-022-01217-z", "Hadinger, Nora", corresponding_author),
         corresponding_author = ifelse(doi == "10.1093/brain/awaa360", "Hoeftberger, Romana", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awq115", "Hoeglinger, Guenter U.", corresponding_author),
          corresponding_author = ifelse(doi == "10.1038/s41593-019-0377-4", "Henaff, Olivier J.", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awad236", "Ibanez, Agustin", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awaa341", "Kuehn, Andrea A.", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awu258", "Kuehn, Andrea A.", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awv109", "Kuehn, Andrea A.", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awx016", "Kuehl, Joern-Sven", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp112", "Koelker, Stefan", corresponding_author),
          corresponding_author = ifelse(doi == "10.1038/nn.2656", "Klaembt, Christian", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awq021", "Kloeppel, Stefan", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp081", "Kloeppel, Stefan", corresponding_author),
          corresponding_author = ifelse(doi == "10.1038/nn.2280", "Knoell, Bernd", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/aww170", "Kuepper, Hanna", corresponding_author),
          corresponding_author = ifelse(doi == "10.1038/s41593-021-00917-2", "Karadottir, Ragnhildur Thora", corresponding_author),
          corresponding_author = ifelse(doi == "10.1038/nn.3102", "Kraemer, Helmut", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awv002", "Lasmezas, Corinne I.", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awq162", "Lehericy, Stephane", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/aws078", "Lhommee, Eugenie", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awx275", "Lleo, Alberto", corresponding_author),
          corresponding_author = ifelse(doi == "10.1038/nn.3773", "Lena, Clement", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awab465", "Luenemann, Jan D.", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awu160", "Lochmueller, Hanns", corresponding_author),
          corresponding_author = ifelse(doi == "10.1038/nn.3160", "Lopez-Bendito, Guillermina", corresponding_author),
          corresponding_author = ifelse(doi == "10.1038/nn.2763", "Luescher, Christian", corresponding_author),
          corresponding_author = ifelse(doi == "10.1038/nn.2367", "Luescher, Christian", corresponding_author),
          corresponding_author = ifelse(doi == "10.1038/nn.3849", "Luescher, Christian", corresponding_author),
          corresponding_author = ifelse(doi == "10.1038/nn.4102", "Luethi, Andreas", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awq149", "Magloczky, Zsofia", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awn346", "Maihoefner, Christian", corresponding_author),
          corresponding_author = ifelse(doi == "10.1038/s41593-018-0162-9", "Marin, Oscar", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awt074", "Marti, Ramon", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awr265", "Mauguiere, Francois", corresponding_author),
          corresponding_author = ifelse(doi == "10.1038/nn.3660", "Miesenboeck, Gero", corresponding_author),
          corresponding_author = ifelse(doi == "10.1038/nn.2687", "Miesenboeck, Gero", corresponding_author),
          corresponding_author = ifelse(doi == "10.1038/s41593-023-01369-6", "Mueller, Ruth", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awr222", "Mueller, Hans Werner", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp172", "Mueller, Ulrich", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awt079", "Mueller, Ralph-Axel", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awt247", "Mueller, Martijn L. T. M.", corresponding_author),
          corresponding_author = ifelse(doi == "10.1038/s41593-018-0251-9", "Matyas, Ferenc", corresponding_author),
          corresponding_author = ifelse(doi == "10.1038/s41593-020-0620-z", "Matyas, Ferenc", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp023", "Munoz, Francisco J.", corresponding_author),
          corresponding_author = ifelse(doi == "10.1038/nn.3682", "Naegerl, U. Valentin", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awv117", "Nemeth, Andrea H.", corresponding_author),
          corresponding_author = ifelse(doi == "10.1038/nn.4291", "Olafsdottir, H. Freyja", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awx383", "Otarula, Karina A. Gonzalez", corresponding_author),
          corresponding_author = ifelse(doi == "10.1038/nn.2499", "Pare, Denis", corresponding_author),
          corresponding_author = ifelse(doi == "10.1038/nn.2305", "Pare, Denis", corresponding_author),
          corresponding_author = ifelse(doi == "10.1038/s41593-018-0249-3", "Pinol, Ramon A.", corresponding_author),
          corresponding_author = ifelse(doi == "10.1038/s41593-018-0292-0", "Polania, Rafael", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awq212", "Peran, Patrice", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awq311", "Perennou, Dominic", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awv342", "Perez-Duenas, Belen", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awz230", "Perez-Navarro, Esther", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awad006", "Poetter-Nerger, Monika", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awy242", "Rueber, Theodor", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awac105", "Renteria, Miguel E.", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awad431", "Restrepo-Martinez, Miguel", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awad227", "Rodriguez-Oroz, Maria Cruz", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awz167", "Ruhe, Henricus G.", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awu202", "Sablonniere, Bernard", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awx269", "Santamaria-Garcia, Hernando", corresponding_author),  
          corresponding_author = ifelse(doi == "10.1093/brain/awz102", "Schuele, Rebecca", corresponding_author), 
           corresponding_author = ifelse(doi == "10.1093/brain/awx273", "Schoels, Ludger", corresponding_author),
           corresponding_author = ifelse(doi == "10.1093/brain/awv255", "Schoels, Ludger", corresponding_author),
           corresponding_author = ifelse(doi == "10.1093/brain/awac155", "Schoels, Ludger", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awab288", "Schoenberger, Jan", corresponding_author),
          corresponding_author = ifelse(doi == "10.1038/nn.2320", "Suedhof, Thomas C.", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awz171", "Series, Peggy", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awv067", "Steinhaeuser, Christian", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awae061", "Tamgueney, Gueltekin", corresponding_author),
          corresponding_author = ifelse(doi == "10.1038/s41593-018-0205-2", "Tamas, Gabor", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/aws254", "Toenges, Lars", corresponding_author),
          corresponding_author = ifelse(doi == "10.1038/s41593-023-01551-w", "Tome, Douglas Feitosa", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp346", "Trivino, Monica", corresponding_author),
          corresponding_author = ifelse(doi == "10.1038/nn.2569", "Tschoep, Matthias H.", corresponding_author),
          corresponding_author = ifelse(doi == "10.1038/s41593-018-0286-y", "Tschoep, Matthias H.", corresponding_author),
          corresponding_author = ifelse(doi == "10.1038/nn.3219", "Tschoep, Matthias H.", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awy324", "Wagnon, Jacy L.", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awt326", "Zuechner, Stephan", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awu078", "Zoerner, Bjoern", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awn306", "Sander, T.", corresponding_author),
          corresponding_author = ifelse(doi == "10.1162/jocn.2009.21321", "Shafto, Meredith A.", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp191", "Zerr, I", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awn314", "Kipps, C.M.", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awn336", "Butler, C.R.", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp183", "Coleman, M.R.", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp135", "Ramachandran, V.S.", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp294", "Hanna, MG", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp080", "Goldenberg, G", corresponding_author),
          corresponding_author = ifelse(doi == "10.1162/jocn_a_00906", "Cohen, AO", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awq010", "Carhart-Harris, RL", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awn313", "Braun, KPJ", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp156", "Hutchinson, M", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp220", "Stone, J", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp222", "Schevon, CA", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awn316", "Breteler, MMB", corresponding_author),
          corresponding_author = ifelse(doi == "10.1162/jocn.2009.21309", "Ralph, MAL", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp157", "Rao, SM", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/aww246", "Corlier, J", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awt244", "Schott, GD", corresponding_author),
          corresponding_author = ifelse(doi == "10.1162/jocn_a_02094", "Skalaban, LJ", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awn335", "Brown, SC", corresponding_author),
          corresponding_author = ifelse(doi == "10.1162/jocn_a_01621", "Kelly, LJ", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/aws151", "Zuberi, SM", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awu395", "Schott, GD", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awr314", "Schott, GD", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awad238", "Armangu, T", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp103", "Tesink, CMJY", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awn344", "Swinnen, SP", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awq007", "Chinnery, PF", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp007", "Schuff, N", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/aws122", "Steinfeld, R", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp176", "Bentley, P", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awn298", "Burton, EJ", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp244", "Montplaisir, JY", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/aws209", "Braulke, T", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp209", "Stoessl, AJ", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awn345", "Kriz, J", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awn329", "Gaillard, WD", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awn322", "Prescott, IA", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/aws037", "Lemon, RN", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp137", "Agirre-Arrizubieta, Z", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp047", "von Lehe, M", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp243", "Gudziol, V", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp054", "Strafella, AP", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awad326", "Brennan, KC", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp026", "Rothwell, PM", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/aws093", "Montplaisir, JY", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp059", "Wharton, SB", corresponding_author),
          corresponding_author = ifelse(doi == "10.1038/nn.2353", "Field, GD", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp106", "Evangelou, N", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awn301", "Pelletier, D", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awt202", "Jinnah, HA", corresponding_author),
          corresponding_author = ifelse(doi == "10.1162/jocn.2010.21572", "Somerville, LH", corresponding_author),
          corresponding_author = ifelse(doi == "10.1038/s41593-021-00866-w", "Kolling, N", corresponding_author),
          corresponding_author = ifelse(doi == "10.1162/jocn.2009.21191", "Coslett, HB", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp208", "Andreassen, CS", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awn320", "Jagust, WJ", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp301", "Cools, R", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awn308", "Moore, BCJ", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awn294", "Welter, ML", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp327", "Jacquin-Courtois, S", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp256", "Baron-Van Evercooren, A", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awq022", "Timmermann, L", corresponding_author),
          corresponding_author = ifelse(doi == "10.1162/jocn.2009.21052", "Marsh, AA", corresponding_author),
          corresponding_author = ifelse(doi == "10.1162/jocn_a_00614", "Taylor, JSH", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awn275", "Dineen, RA", corresponding_author),
          corresponding_author = ifelse(doi == "10.1162/jocn_a_00007", "Ralph, MAL", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp114", "Duncan, JS", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awn109", "Neumann, H", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awn289", "Bushby, KMD", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp028", "Blumenfeld, H", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/aws234", "Schneider, JA", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp027", "Blumenfeld, H", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp182", "Helmstaedter, C", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp124", "Dietz, V", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awn355", "Mochel, F", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp265", "Boyd, CAR", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp111", "Del Cul, A", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awn363", "Roze, E", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp334", "Inglese, M", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp154", "Sparing, R", corresponding_author),
          corresponding_author = ifelse(doi == "10.1162/jocn_a_00790", "Iordan, MC", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awq013", "Jinnah, HA", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp211", "Anheim, M", corresponding_author),
          corresponding_author = ifelse(doi == "10.1038/s41593-024-01627-1", "Samieri, C", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp165", "Baier, B", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp299", "Hummel, FC", corresponding_author),
          corresponding_author = ifelse(doi == "10.1162/jocn_a_00218", "Shafto, M", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp148", "Rosi, S", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp213", "Quartarone, A", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp228", "Comabella, M", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awq294", "Bushby, K", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp234", "Lees, AJ", corresponding_author),
          corresponding_author = ifelse(doi == "10.1093/brain/awp164", "Chan, A", corresponding_author))
```
# Merge with predicted+labeled data
```{r}
predicted_data<- read.csv("updating_name_value.csv") %>% 
  mutate(gender = as.factor(gender),
         bipoc  = as.factor(bipoc))  %>% 
  mutate(gender = recode(gender, "m" = "0", "f" = "1"))

first_author_data <- predicted_data %>%
  select(full_name, bipoc, gender) %>%
  rename(first_author_bipoc = bipoc, first_author_gender = gender) %>% 
 mutate(first_author_gender_bipoc = ifelse(is.na(first_author_gender) | is.na(first_author_bipoc), NA, paste0(first_author_gender, first_author_bipoc))) %>% 
  distinct()

last_author_data <- predicted_data %>%
  select(full_name, bipoc, gender) %>%
  rename(last_author_bipoc = bipoc, last_author_gender = gender) %>% 
 mutate(last_author_gender_bipoc = ifelse(is.na(last_author_gender) | is.na(last_author_bipoc), NA, paste0(last_author_gender, last_author_bipoc)))%>% 
  distinct()

corresponding_author_data <- predicted_data %>%
  select(full_name, bipoc, gender) %>%
  rename(corresponding_author_bipoc = bipoc, corresponding_author_gender = gender)%>% 
  mutate(corresponding_author_gender_bipoc = paste0(corresponding_author_gender, corresponding_author_bipoc)) %>% 
  mutate(corresponding_author_gender_bipoc = ifelse(is.na(corresponding_author_gender) | is.na(corresponding_author_bipoc), NA, paste0(corresponding_author_gender, corresponding_author_bipoc)))%>% 
  distinct()

merged_clean_data<- manual_clean_data %>%
  left_join(first_author_data, by = c("first_author" = "full_name")) %>%
  left_join(last_author_data, by = c("last_author" = "full_name"))%>%
  left_join(corresponding_author_data, by = c("corresponding_author" = "full_name")) %>% 
  mutate(fl_gender = case_when(
    first_author_gender == "0" & last_author_gender == "1" ~ "mm",
    first_author_gender == "1" & last_author_gender == "1" ~ "Wm",
    first_author_gender == "0" & last_author_gender == "0" ~ "mw",
    first_author_gender == "1" & last_author_gender == "0" ~ "WW"
  ))%>%
  mutate(fl_bipoc = case_when(
    first_author_bipoc == 0 & last_author_bipoc == 0 ~ "ww",
    first_author_bipoc == 0 & last_author_bipoc == 1 ~ "wb",
    first_author_bipoc == 1 & last_author_bipoc == 0 ~ "bw",
    first_author_bipoc == 1 & last_author_bipoc == 1 ~ "bb"
  )) %>% 
  mutate(fl_gender = tolower(fl_gender))

# if corresponding author overlap with first author, coded as 1, if overlap with last author, coded as 2, no overlap coded as 0
merged_clean_data <- merged_clean_data %>%
  mutate(
    overlap_corr_author = case_when(
      corresponding_author == first_author ~ "1",
      corresponding_author == last_author ~ "2",
      TRUE ~ "0"
    )
  )  %>% 
  select(-both_match, -none_match,-first_author_last_name,-last_author_last_name, -corresponding_author, -first_author, -last_author)

#write.csv(merged_clean_data, file= "updating_cr_data.csv")
```

# Recode rest of the info
```{r}
gender_bipoc<- read.csv("updating_gender_bipoc_data.csv") %>% 
  distinct(doi, all_men, all_women, all_white, all_bipoc) 

full_data<- merged_clean_data %>% 
  left_join(gender_bipoc, by = "doi")%>% 
  select(-article_title, -reprint_addresses,-funding_orgs) %>% 
  glimpse()

write.csv(full_data, file = "updating_full_data.csv", row.names = FALSE)
```
